import { useEffect, useRef } from 'react';
import { Renderer, Program, Mesh, Triangle } from 'ogl';
import './Plasma.css';
const hexToRgb=hex=>{const r=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);return r?[parseInt(r[1],16)/255,parseInt(r[2],16)/255,parseInt(r[3],16)/255]:[1,.5,.2]};
const vertex=`#version 300 es
precision highp float;in vec2 position;in vec2 uv;out vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,0.0,1.0);}`;
const fragment=`#version 300 es
precision highp float;uniform vec2 iResolution;uniform float iTime;uniform vec3 uCustomColor;uniform float uSpeed;uniform float uDirection;uniform float uScale;uniform float uOpacity;uniform vec2 uMouse;uniform float uMouseInteractive;out vec4 fragColor;
void mainImage(out vec4 o,vec2 C){vec2 center=iResolution.xy*.5;C=(C-center)/uScale+center;vec2 mouseOffset=(uMouse-center)*.0002;C+=mouseOffset*length(C-center)*step(.5,uMouseInteractive);float i,d,z,T=iTime*uSpeed*uDirection;vec3 O,p,S;for(vec2 r=iResolution.xy,Q;++i<60.;O+=o.w/d*o.xyz){p=z*normalize(vec3(C-.5*r,r.y));p.z-=4.;S=p;d=p.y-T;p.x+=.4*(1.+p.y)*sin(d+p.x*.1)*cos(.34*d+p.x*.05);Q=p.xz*=mat2(cos(p.y+vec4(0,11,33,0)-T));z+=d=abs(sqrt(length(Q*Q))-.25*(5.+S.y))/3.+8e-4;o=1.+sin(S.y+p.z*.5+S.z-length(S-p)+vec4(2,1,0,8));}o.xyz=tanh(O/1e4);}bool finite1(float x){return !(isnan(x)||isinf(x));}vec3 sanitize(vec3 c){return vec3(finite1(c.r)?c.r:0.,finite1(c.g)?c.g:0.,finite1(c.b)?c.b:0.);}void main(){vec4 o=vec4(0.);mainImage(o,gl_FragCoord.xy);vec3 rgb=sanitize(o.rgb);float intensity=(rgb.r+rgb.g+rgb.b)/3.;vec3 finalColor=intensity*uCustomColor;float alpha=length(rgb)*uOpacity;fragColor=vec4(finalColor,alpha);}`;
export default function Plasma({color='#7779ff',speed=.45,direction='forward',scale=1.25,opacity=.32,mouseInteractive=true}){const ref=useRef(null),mouse=useRef({x:0,y:0});useEffect(()=>{if(!ref.current)return;const el=ref.current;let renderer;try{renderer=new Renderer({webgl:2,alpha:true,antialias:false,dpr:Math.min(devicePixelRatio||1,1.5)})}catch{return}const gl=renderer.gl;if(!gl)return;const canvas=gl.canvas;Object.assign(canvas.style,{display:'block',width:'100%',height:'100%'});el.appendChild(canvas);const program=new Program(gl,{vertex,fragment,uniforms:{iTime:{value:0},iResolution:{value:new Float32Array([1,1])},uCustomColor:{value:new Float32Array(hexToRgb(color))},uSpeed:{value:speed*.4},uDirection:{value:direction==='reverse'?-1:1},uScale:{value:scale},uOpacity:{value:opacity},uMouse:{value:new Float32Array([0,0])},uMouseInteractive:{value:mouseInteractive?1:0}}});const mesh=new Mesh(gl,{geometry:new Triangle(gl),program});const move=e=>{if(!mouseInteractive)return;const r=el.getBoundingClientRect(),u=program.uniforms.uMouse.value;mouse.current={x:e.clientX-r.left,y:e.clientY-r.top};u[0]=mouse.current.x;u[1]=mouse.current.y};el.addEventListener('mousemove',move);const size=()=>{const r=el.getBoundingClientRect();renderer.setSize(Math.max(1,r.width|0),Math.max(1,r.height|0));const u=program.uniforms.iResolution.value;u[0]=gl.drawingBufferWidth;u[1]=gl.drawingBufferHeight};const ro=new ResizeObserver(size);ro.observe(el);size();let raf=0,visible=true,lost=false,t0=performance.now();const loop=t=>{if(lost||!visible)return;program.uniforms.iTime.value=(t-t0)*.001;renderer.render({scene:mesh});raf=requestAnimationFrame(loop)};const io=new IntersectionObserver(([e])=>{const prev=visible;visible=e.isIntersecting;if(visible&&!prev&&!lost)raf=requestAnimationFrame(loop)});io.observe(el);const lose=e=>{e.preventDefault();lost=true;cancelAnimationFrame(raf)};const restore=()=>{lost=false;if(visible)raf=requestAnimationFrame(loop)};canvas.addEventListener('webglcontextlost',lose);canvas.addEventListener('webglcontextrestored',restore);raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);ro.disconnect();io.disconnect();el.removeEventListener('mousemove',move);canvas.removeEventListener('webglcontextlost',lose);canvas.removeEventListener('webglcontextrestored',restore);try{el.removeChild(canvas)}catch{}}},[color,speed,direction,scale,opacity,mouseInteractive]);return <div ref={ref} className="plasma-container"/>}